fullname=input("Name:")
age=input("Age:")
birthdate=input("Date of Birth:")
birthplace=input("Place of Birth:")
dialect=input("Dialect:")
address=input("Address:")
origin=input("Nationality")
religion=input("Religion:")
status=input("Civil Status:")
sex=input("Sex:")
father=input("Father's Name:")
mother=input("Mother's Name:")
email=input("Email:")
phone=input("Phone No.:")

print("\n\n\nConclusion:\n Hi! my name is"+ fullname +",I am",age,"years old,And I was born on",birthdate,"at" ,birthplace,".My nationality is"+ origin +",My father's name is"+ father +"and my mother's name is"+ mother +". I live in" + address,",you can contact me on", email ,"or at", phone,".")